### PR TITLE
added readline require

### PR DESCRIPTION
**Pull request by dsisejkovic**
I tried out the example. It works, but the 'readline' module needs to be required.

### CODE REVIEW

**Comment by IonicaBizau** [comment]
Oh, thanks for heads-up, @dsisejkovic! :sparkles: 

Instead of `requir`ing the module, just [delete these lines](https://github.com/IonicaBizau/youtube-api/blob/8eadcf965acd0bbdc7388a8a382efbf1522f32d8/example/index.js#L34-L38)–looks like the read line is not used.

**Comment by IonicaBizau** [comment]
And fix this typo too: https://github.com/IonicaBizau/youtube-api/blob/8eadcf965acd0bbdc7388a8a382efbf1522f32d8/example/index.js#L14 :smile:

**Comment by dsisejkovic** [comment]
Hope that's all :)

**Comment by IonicaBizau** [comment]
:ship: `1.2.1` :tada: Thanks! :apple:

**Pull request merged**
