### PR TITLE
Fixed wrong Markdown

### PR DESCRIPTION
**Pull request by DerEnderKeks**
Added more newlines to prevent wrong Markdown rendering (screenshot of the npm page: https://keks.cf/-GD1cG1w.png)

### CODE REVIEW

**Comment by IonicaBizau** [comment]
@DerEnderKeks Somehow I missed this pull request. Sorry, how is that wrong? Or how does this fix the problem?

**Comment by DerEnderKeks** [comment]
That's wrong: https://keks.cf/5OWTch-1.png (below https://www.npmjs.com/package/youtube-api#memo-documentation)
And I can't explain why more newlines fix the problem, but apparently that's how Markdown works.

**Comment by IonicaBizau** [comment]
Ahhh! I see! Good eyes! 👀

**Comment by DerEnderKeks** [comment]
Ok, I just screwed my fork. Can you do that change real quick? Otherwise I would have to open a new PR :/

**Comment by IonicaBizau** [comment]
Will take care of it tomorrow.

**Comment by IonicaBizau** [comment]
This landed on master! :tada: Thanks!

**Pull request closed without merging**
